# Generated by Django 5.2.5 on 2025-11-03 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepageUser', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
