# Generated by Django 5.2.5 on 2025-10-19 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_alerts', models.BooleanField(default=False)),
                ('is_group_activity', models.BooleanField(default=False)),
                ('is_individual_activity', models.BooleanField(default=False)),
                ('is_sport', models.BooleanField(default=False)),
                ('is_art', models.BooleanField(default=False)),
                ('is_psychology', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
