# Generated by Django 5.2.5 on 2025-10-19 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('scheduleID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('space', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sport', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'Mixto')], max_length=1)),
                ('modality', models.CharField(choices=[('E', 'Equipos'), ('I', 'Individual'), ('X', 'Mixto')], max_length=1)),
                ('start_date', models.DateField()),
                ('max_participants', models.PositiveIntegerField(default=0)),
                ('current_participants', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('P', 'Por empezar'), ('I', 'En progreso'), ('F', 'Finalizado')], default='P', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('members', models.TextField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournaments.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participantId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournaments.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournaments.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeScore', models.IntegerField(default=0)),
                ('guestScore', models.IntegerField(default=0)),
                ('played', models.BooleanField(default=False)),
                ('guest_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_games_as_player', to='tournaments.participant')),
                ('guest_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_games', to='tournaments.team')),
                ('home_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_games_as_player', to='tournaments.participant')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_games', to='tournaments.team')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.schedule')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament')),
            ],
        ),
    ]
