# Generated by Django 5.2.6 on 2025-10-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
