# Generated by Django 5.2.5 on 2025-10-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_participant_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='goals_conceded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='goals_scored',
            field=models.IntegerField(default=0),
        ),
    ]
