# Generated by Django 5.2.5 on 2025-11-09 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_participant_goals_conceded_participant_goals_scored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentgame',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='tournaments.tournament'),
        ),
    ]
