/* ---------------------------
   django_content_type
   --------------------------- */
CREATE TABLE django_content_type (
    id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    app_label VARCHAR2(100) NOT NULL,
    model VARCHAR2(100) NOT NULL,
    CONSTRAINT django_content_type_pkey PRIMARY KEY (id),
    CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model)
);

-- ---------------------------
-- auth_group
-- ---------------------------
CREATE TABLE auth_group (
    id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name VARCHAR2(150) NOT NULL,
    CONSTRAINT auth_group_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_name_key UNIQUE (name)
);

CREATE INDEX auth_group_name_a6ea08ec_like ON auth_group(name);

-- ---------------------------
-- auth_permission
-- ---------------------------
CREATE TABLE auth_permission (
    id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name VARCHAR2(255) NOT NULL,
    content_type_id NUMBER(10) NOT NULL,
    codename VARCHAR2(100) NOT NULL,
    CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
    CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename),
    CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co
      FOREIGN KEY (content_type_id)
      REFERENCES django_content_type (id)
      DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX auth_permission_content_type_id_2f476e4b ON auth_permission(content_type_id);

-- ---------------------------
-- auth_group_permissions
-- ---------------------------
CREATE TABLE auth_group_permissions (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    group_id NUMBER(10) NOT NULL,
    permission_id NUMBER(10) NOT NULL,
    CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id),
    CONSTRAINT auth_group_permissions_permission_id_84c5c92e_fk_auth_perm
      FOREIGN KEY (permission_id)
      REFERENCES auth_permission (id)
      DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id
      FOREIGN KEY (group_id)
      REFERENCES auth_group (id)
      DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON auth_group_permissions(group_id);
CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON auth_group_permissions(permission_id);

-- ---------------------------
-- login_faculty
-- ---------------------------
CREATE TABLE login_faculty (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name VARCHAR2(30) NOT NULL,
    CONSTRAINT login_faculty_pkey PRIMARY KEY (id),
    CONSTRAINT login_faculty_name_key UNIQUE (name)
);

CREATE INDEX login_faculty_name_0f9bfd7c_like ON login_faculty(name);

-- ---------------------------
-- login_customuser
-- ---------------------------
CREATE TABLE login_customuser (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    password VARCHAR2(128) NOT NULL,
    last_login TIMESTAMP WITH TIME ZONE,
    is_superuser CHAR(1) NOT NULL,   -- 'Y'/'N'
    username VARCHAR2(150) NOT NULL,
    first_name VARCHAR2(150) NOT NULL,
    last_name VARCHAR2(150) NOT NULL,
    email VARCHAR2(254) NOT NULL,
    is_staff CHAR(1) NOT NULL,       -- 'Y'/'N'
    is_active CHAR(1) NOT NULL,      -- 'Y'/'N'
    date_joined TIMESTAMP WITH TIME ZONE NOT NULL,
    faculty_id NUMBER(19),
    gender VARCHAR2(1) NOT NULL,
    identification VARCHAR2(20) NOT NULL,
    CONSTRAINT login_customuser_pkey PRIMARY KEY (id),
    CONSTRAINT login_customuser_username_key UNIQUE (username),
    CONSTRAINT login_customuser_faculty_id_032109d2_fk_login_faculty_id
      FOREIGN KEY (faculty_id)
      REFERENCES login_faculty (id)
      DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX login_customuser_faculty_id_032109d2 ON login_customuser(faculty_id);
CREATE INDEX login_customuser_username_ca00b3f5_like ON login_customuser(username);

-- ---------------------------
-- login_customuser_groups
-- ---------------------------
CREATE TABLE login_customuser_groups (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    customuser_id NUMBER(19) NOT NULL,
    group_id NUMBER(10) NOT NULL,
    CONSTRAINT login_customuser_groups_pkey PRIMARY KEY (id),
    CONSTRAINT login_customuser_groups_customuser_id_group_id_280bd5c2_uniq UNIQUE (customuser_id, group_id),
    CONSTRAINT login_customuser_gro_customuser_id_50381d88_fk_login_cus
      FOREIGN KEY (customuser_id)
      REFERENCES login_customuser (id)
      DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT login_customuser_groups_group_id_639d055d_fk_auth_group_id
      FOREIGN KEY (group_id)
      REFERENCES auth_group (id)
      DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX login_customuser_groups_customuser_id_50381d88 ON login_customuser_groups(customuser_id);
CREATE INDEX login_customuser_groups_group_id_639d055d ON login_customuser_groups(group_id);

-- ---------------------------
-- auth_permission -> login_customuser_user_permissions
-- ---------------------------
CREATE TABLE login_customuser_user_permissions (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    customuser_id NUMBER(19) NOT NULL,
    permission_id NUMBER(10) NOT NULL,
    CONSTRAINT login_customuser_user_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT login_customuser_user_pe_customuser_id_permission_afb8143d_uniq UNIQUE (customuser_id, permission_id),
    CONSTRAINT login_customuser_use_customuser_id_c6f5792f_fk_login_cus
      FOREIGN KEY (customuser_id)
      REFERENCES login_customuser (id)
      DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT login_customuser_use_permission_id_2b8ae21e_fk_auth_perm
      FOREIGN KEY (permission_id)
      REFERENCES auth_permission (id)
      DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX login_customuser_user_permissions_customuser_id_c6f5792f ON login_customuser_user_permissions(customuser_id);
CREATE INDEX login_customuser_user_permissions_permission_id_2b8ae21e ON login_customuser_user_permissions(permission_id);

-- ---------------------------
-- activities_activity
-- ---------------------------
CREATE TABLE activities_activity (
    activityId NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name VARCHAR2(200) NOT NULL,
    description CLOB NOT NULL,
    location VARCHAR2(200) NOT NULL,
    type VARCHAR2(20),
    category VARCHAR2(20),
    is_published CHAR(1) NOT NULL,           -- 'Y'/'N'
    requires_registration CHAR(1) NOT NULL,  -- 'Y'/'N'
    max_capacity NUMBER(10),
    CONSTRAINT activities_activity_pkey PRIMARY KEY (activityId),
    CONSTRAINT activities_activity_max_capacity_check CHECK (max_capacity IS NULL OR max_capacity >= 0)
);

-- ---------------------------
-- activities_schedule
-- ---------------------------
CREATE TABLE activities_schedule (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    day VARCHAR2(10) NOT NULL,
    start_time VARCHAR2(8) NOT NULL, -- 'HH24:MI:SS'
    end_time VARCHAR2(8) NOT NULL,   -- 'HH24:MI:SS'
    activity_id NUMBER(10) NOT NULL,
    CONSTRAINT activities_schedule_pkey PRIMARY KEY (id),
    CONSTRAINT activities_schedule_activity_id_cece9c52_fk_activitie
      FOREIGN KEY (activity_id)
      REFERENCES activities_activity (activityId)
      DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX activities_schedule_activity_id_cece9c52 ON activities_schedule(activity_id);

-- ---------------------------
-- activities_activityreview
-- ---------------------------
CREATE TABLE activities_activityreview (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    rating NUMBER(5) NOT NULL,
    comment CLOB,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    is_read CHAR(1) NOT NULL,            -- 'Y'/'N'
    activity_id NUMBER(10) NOT NULL,
    user_id NUMBER(19) NOT NULL,
    CONSTRAINT activities_activityreview_pkey PRIMARY KEY (id),
    CONSTRAINT activities_activityr_activity_id_8134ac5b_fk_activitie
      FOREIGN KEY (activity_id)
      REFERENCES activities_activity (activityId)
      DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT activities_activityr_user_id_4a13a414_fk_login_cus
      FOREIGN KEY (user_id)
      REFERENCES login_customuser (id)
      DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT activities_activityreview_rating_check CHECK (rating >= 0)
);

CREATE INDEX activities_activityreview_activity_id_8134ac5b ON activities_activityreview(activity_id);
CREATE INDEX activities_activityreview_user_id_4a13a414 ON activities_activityreview(user_id);

-- ---------------------------
-- activities_enrollment
-- ---------------------------
CREATE TABLE activities_enrollment (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    registered_at TIMESTAMP WITH TIME ZONE NOT NULL,
    activity_id NUMBER(10) NOT NULL,
    user_id NUMBER(19) NOT NULL,
    schedule_id NUMBER(19),
    confirmed CHAR(1) NOT NULL,            -- 'Y'/'N'
    confirmed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT activities_enrollment_pkey PRIMARY KEY (id),
    CONSTRAINT activities_enrollment_user_id_activity_id_ecfe66e5_uniq UNIQUE (user_id, activity_id),
    CONSTRAINT activities_enrollmen_activity_id_2d054d48_fk_activitie
      FOREIGN KEY (activity_id)
      REFERENCES activities_activity (activityId)
      DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT activities_enrollmen_schedule_id_8a64bf23_fk_activitie
      FOREIGN KEY (schedule_id)
      REFERENCES activities_schedule (id)
      DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT activities_enrollment_user_id_714b6695_fk_login_customuser_id
      FOREIGN KEY (user_id)
      REFERENCES login_customuser (id)
      DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX activities_enrollment_activity_id_2d054d48 ON activities_enrollment(activity_id);
CREATE INDEX activities_enrollment_schedule_id_8a64bf23 ON activities_enrollment(schedule_id);
CREATE INDEX activities_enrollment_user_id_714b6695 ON activities_enrollment(user_id);

-- ---------------------------
-- activities_participation
-- ---------------------------
CREATE TABLE activities_participation (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    date_registered TIMESTAMP WITH TIME ZONE NOT NULL,
    attendance_date DATE,
    attendance_time VARCHAR2(8),
    activity_id NUMBER(10) NOT NULL,
    user_id NUMBER(19) NOT NULL,
    schedule_id NUMBER(19),
    CONSTRAINT activities_participation_pkey PRIMARY KEY (id),
    CONSTRAINT activities_participation_user_id_activity_id_atte_d984d0cb_uniq UNIQUE (user_id, activity_id, attendance_date),
    CONSTRAINT activities_participa_activity_id_398b3752_fk_activitie
      FOREIGN KEY (activity_id)
      REFERENCES activities_activity (activityId)
      DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT activities_participa_schedule_id_b55d81e2_fk_activitie
      FOREIGN KEY (schedule_id)
      REFERENCES activities_schedule (id)
      DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT activities_participa_user_id_4f51bded_fk_login_cus
      FOREIGN KEY (user_id)
      REFERENCES login_customuser (id)
      DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX activities_participation_activity_id_398b3752 ON activities_participation(activity_id);
CREATE INDEX activities_participation_schedule_id_b55d81e2 ON activities_participation(schedule_id);
CREATE INDEX activities_participation_user_id_4f51bded ON activities_participation(user_id);

-- ---------------------------
-- activities_evento
-- ---------------------------
CREATE TABLE activities_evento (
    id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    titulo VARCHAR2(100) NOT NULL,
    fecha TIMESTAMP WITH TIME ZONE NOT NULL,
    categoria VARCHAR2(50) NOT NULL,
    CONSTRAINT activities_evento_pkey PRIMARY KEY (id)
);

-- ---------------------------
-- social_projects_socialproject
-- ---------------------------
CREATE TABLE social_projects_socialproject (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name VARCHAR2(100) NOT NULL,
    description CLOB NOT NULL,
    location VARCHAR2(100),
    start_date DATE,
    end_date DATE,
    CONSTRAINT social_projects_socialproject_pkey PRIMARY KEY (id)
);

-- ---------------------------
-- social_projects_socialprojectenrollment
-- ---------------------------
CREATE TABLE social_projects_socialprojectenrollment (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    enrolled_at TIMESTAMP WITH TIME ZONE NOT NULL,
    project_id NUMBER(19) NOT NULL,
    user_id NUMBER(19) NOT NULL,
    CONSTRAINT social_projects_socialprojectenrollment_pkey PRIMARY KEY (id),
    CONSTRAINT social_projects_socialpr_user_id_project_id_07cd27ee_uniq UNIQUE (user_id, project_id),
    CONSTRAINT social_projects_soci_project_id_607ef32c_fk_social_pr
      FOREIGN KEY (project_id)
      REFERENCES social_projects_socialproject (id)
      DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT social_projects_soci_user_id_50dac806_fk_login_cus
      FOREIGN KEY (user_id)
      REFERENCES login_customuser (id)
      DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX social_projects_socialprojectenrollment_project_id_607ef32c ON social_projects_socialprojectenrollment(project_id);
CREATE INDEX social_projects_socialprojectenrollment_user_id_50dac806 ON social_projects_socialprojectenrollment(user_id);

-- ---------------------------
-- tournaments_tournament
-- ---------------------------
CREATE TABLE tournaments_tournament (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name VARCHAR2(100) NOT NULL,
    sport VARCHAR2(50) NOT NULL,
    gender VARCHAR2(1) NOT NULL,
    modality VARCHAR2(1) NOT NULL,
    start_date DATE NOT NULL,
    max_participants NUMBER(10) NOT NULL,
    current_participants NUMBER(10) NOT NULL,
    status VARCHAR2(1) NOT NULL,
    CONSTRAINT tournaments_tournament_pkey PRIMARY KEY (id),
    CONSTRAINT tournaments_tournament_max_participants_check CHECK (max_participants >= 0),
    CONSTRAINT tournaments_tournament_current_participants_check CHECK (current_participants >= 0)
);

-- ---------------------------
-- tournaments_team
-- ---------------------------
CREATE TABLE tournaments_team (
    teamId NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name VARCHAR2(100) NOT NULL,
    members CLOB NOT NULL,
    tournament_id NUMBER(19) NOT NULL,
    CONSTRAINT tournaments_team_pkey PRIMARY KEY (teamId),
    CONSTRAINT tournaments_team_tournament_id_b3f02e2a_fk_tournamen
      FOREIGN KEY (tournament_id)
      REFERENCES tournaments_tournament (id)
      DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX tournaments_team_tournament_id_b3f02e2a ON tournaments_team(tournament_id);

-- ---------------------------
-- tournaments_participant
-- ---------------------------
CREATE TABLE tournaments_participant (
    participantId NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name VARCHAR2(100) NOT NULL,
    team_id NUMBER(10),
    tournament_id NUMBER(19) NOT NULL,
    points NUMBER(10) NOT NULL,
    goals_conceded NUMBER(10) NOT NULL,
    goals_scored NUMBER(10) NOT NULL,
    CONSTRAINT tournaments_participant_pkey PRIMARY KEY (participantId),
    CONSTRAINT tournaments_particip_team_id_59ac8a48_fk_tournamen
      FOREIGN KEY (team_id)
      REFERENCES tournaments_team (teamId)
      DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT tournaments_particip_tournament_id_e0202941_fk_tournamen
      FOREIGN KEY (tournament_id)
      REFERENCES tournaments_tournament (id)
      DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX tournaments_participant_team_id_59ac8a48 ON tournaments_participant(team_id);
CREATE INDEX tournaments_participant_tournament_id_e0202941 ON tournaments_participant(tournament_id);

-- ---------------------------
-- tournaments_schedule
-- ---------------------------
CREATE TABLE tournaments_schedule (
    scheduleID NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    date DATE NOT NULL,
    start_time VARCHAR2(8) NOT NULL,
    end_time VARCHAR2(8) NOT NULL,
    capacity NUMBER(10) NOT NULL,
    space VARCHAR2(100) NOT NULL,
    CONSTRAINT tournaments_schedule_pkey PRIMARY KEY (scheduleID),
    CONSTRAINT tournaments_schedule_capacity_check CHECK (capacity >= 0)
);

-- ---------------------------
-- tournaments_tournamentgame
-- ---------------------------
CREATE TABLE tournaments_tournamentgame (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    homeScore NUMBER(10) NOT NULL,
    guestScore NUMBER(10) NOT NULL,
    played CHAR(1) NOT NULL,           -- 'Y'/'N'
    guest_player_id NUMBER(10),
    guest_team_id NUMBER(10),
    home_player_id NUMBER(10),
    home_team_id NUMBER(10),
    schedule_id NUMBER(10) NOT NULL,
    tournament_id NUMBER(19) NOT NULL,
    CONSTRAINT tournaments_tournamentgame_pkey PRIMARY KEY (id),
    CONSTRAINT tournaments_tourname_guest_player_id_b7ee2a48_fk_tournamen
      FOREIGN KEY (guest_player_id)
      REFERENCES tournaments_participant (participantId)
      DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT tournaments_tourname_guest_team_id_9167b045_fk_tournamen
      FOREIGN KEY (guest_team_id)
      REFERENCES tournaments_team (teamId)
      DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT tournaments_tourname_home_player_id_b3452124_fk_tournamen
      FOREIGN KEY (home_player_id)
      REFERENCES tournaments_participant (participantId)
      DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT tournaments_tourname_home_team_id_6db452e6_fk_tournamen
      FOREIGN KEY (home_team_id)
      REFERENCES tournaments_team (teamId)
      DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT tournaments_tourname_schedule_id_e51f5b94_fk_tournamen
      FOREIGN KEY (schedule_id)
      REFERENCES tournaments_schedule (scheduleID)
      DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT tournaments_tourname_tournament_id_d777f9b2_fk_tournamen
      FOREIGN KEY (tournament_id)
      REFERENCES tournaments_tournament (id)
      DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX tournaments_tournamentgame_guest_player_id_b7ee2a48 ON tournaments_tournamentgame(guest_player_id);
CREATE INDEX tournaments_tournamentgame_guest_team_id_9167b045 ON tournaments_tournamentgame(guest_team_id);
CREATE INDEX tournaments_tournamentgame_home_player_id_b3452124 ON tournaments_tournamentgame(home_player_id);
CREATE INDEX tournaments_tournamentgame_home_team_id_6db452e6 ON tournaments_tournamentgame(home_team_id);
CREATE INDEX tournaments_tournamentgame_schedule_id_e51f5b94 ON tournaments_tournamentgame(schedule_id);
CREATE INDEX tournaments_tournamentgame_tournament_id_d777f9b2 ON tournaments_tournamentgame(tournament_id);

-- ---------------------------
-- UserPreference_userpreference
-- ---------------------------
CREATE TABLE UserPreference_userpreference (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    receive_alerts CHAR(1) NOT NULL,           -- 'Y'/'N'
    is_group_activity CHAR(1) NOT NULL,        -- 'Y'/'N'
    is_individual_activity CHAR(1) NOT NULL,   -- 'Y'/'N'
    is_sport CHAR(1) NOT NULL,                 -- 'Y'/'N'
    is_art CHAR(1) NOT NULL,                   -- 'Y'/'N'
    is_psychology CHAR(1) NOT NULL,            -- 'Y'/'N'
    user_id NUMBER(19) NOT NULL,
    CONSTRAINT UserPreference_userpreference_pkey PRIMARY KEY (id),
    CONSTRAINT UserPreference_userpreference_user_id_key UNIQUE (user_id),
    CONSTRAINT UserPreference_userp_user_id_f64e0787_fk_login_cus
      FOREIGN KEY (user_id)
      REFERENCES login_customuser (id)
      DEFERRABLE INITIALLY DEFERRED
);

-- End of schema