-- Table: public.UserPreference_userpreference

-- DROP TABLE IF EXISTS public."UserPreference_userpreference";

CREATE TABLE IF NOT EXISTS public."UserPreference_userpreference"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    receive_alerts boolean NOT NULL,
    is_group_activity boolean NOT NULL,
    is_individual_activity boolean NOT NULL,
    is_sport boolean NOT NULL,
    is_art boolean NOT NULL,
    is_psychology boolean NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT "UserPreference_userpreference_pkey" PRIMARY KEY (id),
    CONSTRAINT "UserPreference_userpreference_user_id_key" UNIQUE (user_id),
    CONSTRAINT "UserPreference_userp_user_id_f64e0787_fk_login_cus" FOREIGN KEY (user_id)
        REFERENCES public.login_customuser (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."UserPreference_userpreference"
    OWNER to bienestaruser;

-- Table: public.activities_activity

-- DROP TABLE IF EXISTS public.activities_activity;

CREATE TABLE IF NOT EXISTS public.activities_activity
(
    "activityId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    location character varying(200) COLLATE pg_catalog."default" NOT NULL,
    type character varying(20) COLLATE pg_catalog."default",
    category character varying(20) COLLATE pg_catalog."default",
    is_published boolean NOT NULL,
    requires_registration boolean NOT NULL,
    max_capacity integer,
    CONSTRAINT activities_activity_pkey PRIMARY KEY ("activityId"),
    CONSTRAINT activities_activity_max_capacity_check CHECK (max_capacity >= 0)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.activities_activity
    OWNER to bienestaruser;

-- Table: public.activities_activityreview

-- DROP TABLE IF EXISTS public.activities_activityreview;

CREATE TABLE IF NOT EXISTS public.activities_activityreview
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    rating smallint NOT NULL,
    comment text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL,
    is_read boolean NOT NULL,
    activity_id integer NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT activities_activityreview_pkey PRIMARY KEY (id),
    CONSTRAINT activities_activityr_activity_id_8134ac5b_fk_activitie FOREIGN KEY (activity_id)
        REFERENCES public.activities_activity ("activityId") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT activities_activityr_user_id_4a13a414_fk_login_cus FOREIGN KEY (user_id)
        REFERENCES public.login_customuser (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT activities_activityreview_rating_check CHECK (rating >= 0)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.activities_activityreview
    OWNER to bienestaruser;
-- Index: activities_activityreview_activity_id_8134ac5b

-- DROP INDEX IF EXISTS public.activities_activityreview_activity_id_8134ac5b;

CREATE INDEX IF NOT EXISTS activities_activityreview_activity_id_8134ac5b
    ON public.activities_activityreview USING btree
    (activity_id ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
-- Index: activities_activityreview_user_id_4a13a414

-- DROP INDEX IF EXISTS public.activities_activityreview_user_id_4a13a414;

CREATE INDEX IF NOT EXISTS activities_activityreview_user_id_4a13a414
    ON public.activities_activityreview USING btree
    (user_id ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;


-- Table: public.activities_enrollment

-- DROP TABLE IF EXISTS public.activities_enrollment;

CREATE TABLE IF NOT EXISTS public.activities_enrollment
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    registered_at timestamp with time zone NOT NULL,
    activity_id integer NOT NULL,
    user_id bigint NOT NULL,
    schedule_id bigint,
    confirmed boolean NOT NULL,
    confirmed_at timestamp with time zone,
    CONSTRAINT activities_enrollment_pkey PRIMARY KEY (id),
    CONSTRAINT activities_enrollment_user_id_activity_id_ecfe66e5_uniq UNIQUE (user_id, activity_id),
    CONSTRAINT activities_enrollmen_activity_id_2d054d48_fk_activitie FOREIGN KEY (activity_id)
        REFERENCES public.activities_activity ("activityId") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT activities_enrollmen_schedule_id_8a64bf23_fk_activitie FOREIGN KEY (schedule_id)
        REFERENCES public.activities_schedule (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT activities_enrollment_user_id_714b6695_fk_login_customuser_id FOREIGN KEY (user_id)
        REFERENCES public.login_customuser (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.activities_enrollment
    OWNER to bienestaruser;
-- Index: activities_enrollment_activity_id_2d054d48

-- DROP INDEX IF EXISTS public.activities_enrollment_activity_id_2d054d48;

CREATE INDEX IF NOT EXISTS activities_enrollment_activity_id_2d054d48
    ON public.activities_enrollment USING btree
    (activity_id ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
-- Index: activities_enrollment_schedule_id_8a64bf23

-- DROP INDEX IF EXISTS public.activities_enrollment_schedule_id_8a64bf23;

CREATE INDEX IF NOT EXISTS activities_enrollment_schedule_id_8a64bf23
    ON public.activities_enrollment USING btree
    (schedule_id ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
-- Index: activities_enrollment_user_id_714b6695

-- DROP INDEX IF EXISTS public.activities_enrollment_user_id_714b6695;

CREATE INDEX IF NOT EXISTS activities_enrollment_user_id_714b6695
    ON public.activities_enrollment USING btree
    (user_id ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;

-- Table: public.activities_evento

-- DROP TABLE IF EXISTS public.activities_evento;

CREATE TABLE IF NOT EXISTS public.activities_evento
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    titulo character varying(100) COLLATE pg_catalog."default" NOT NULL,
    fecha timestamp with time zone NOT NULL,
    categoria character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT activities_evento_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.activities_evento
    OWNER to bienestaruser;


-- Table: public.activities_participation

-- DROP TABLE IF EXISTS public.activities_participation;

CREATE TABLE IF NOT EXISTS public.activities_participation
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    date_registered timestamp with time zone NOT NULL,
    attendance_date date,
    attendance_time time without time zone,
    activity_id integer NOT NULL,
    user_id bigint NOT NULL,
    schedule_id bigint,
    CONSTRAINT activities_participation_pkey PRIMARY KEY (id),
    CONSTRAINT activities_participation_user_id_activity_id_atte_d984d0cb_uniq UNIQUE (user_id, activity_id, attendance_date),
    CONSTRAINT activities_participa_activity_id_398b3752_fk_activitie FOREIGN KEY (activity_id)
        REFERENCES public.activities_activity ("activityId") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT activities_participa_schedule_id_b55d81e2_fk_activitie FOREIGN KEY (schedule_id)
        REFERENCES public.activities_schedule (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT activities_participa_user_id_4f51bded_fk_login_cus FOREIGN KEY (user_id)
        REFERENCES public.login_customuser (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.activities_participation
    OWNER to bienestaruser;
-- Index: activities_participation_activity_id_398b3752

-- DROP INDEX IF EXISTS public.activities_participation_activity_id_398b3752;

CREATE INDEX IF NOT EXISTS activities_participation_activity_id_398b3752
    ON public.activities_participation USING btree
    (activity_id ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
-- Index: activities_participation_schedule_id_b55d81e2

-- DROP INDEX IF EXISTS public.activities_participation_schedule_id_b55d81e2;

CREATE INDEX IF NOT EXISTS activities_participation_schedule_id_b55d81e2
    ON public.activities_participation USING btree
    (schedule_id ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
-- Index: activities_participation_user_id_4f51bded

-- DROP INDEX IF EXISTS public.activities_participation_user_id_4f51bded;

CREATE INDEX IF NOT EXISTS activities_participation_user_id_4f51bded
    ON public.activities_participation USING btree
    (user_id ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;


-- Table: public.activities_schedule

-- DROP TABLE IF EXISTS public.activities_schedule;

CREATE TABLE IF NOT EXISTS public.activities_schedule
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    day character varying(10) COLLATE pg_catalog."default" NOT NULL,
    start_time time without time zone NOT NULL,
    end_time time without time zone NOT NULL,
    activity_id integer NOT NULL,
    CONSTRAINT activities_schedule_pkey PRIMARY KEY (id),
    CONSTRAINT activities_schedule_activity_id_cece9c52_fk_activitie FOREIGN KEY (activity_id)
        REFERENCES public.activities_activity ("activityId") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.activities_schedule
    OWNER to bienestaruser;
-- Index: activities_schedule_activity_id_cece9c52

-- DROP INDEX IF EXISTS public.activities_schedule_activity_id_cece9c52;

CREATE INDEX IF NOT EXISTS activities_schedule_activity_id_cece9c52
    ON public.activities_schedule USING btree
    (activity_id ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;


-- Table: public.login_customuser

-- DROP TABLE IF EXISTS public.login_customuser;

CREATE TABLE IF NOT EXISTS public.login_customuser
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    password character varying(128) COLLATE pg_catalog."default" NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    email character varying(254) COLLATE pg_catalog."default" NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    faculty_id bigint,
    gender character varying(1) COLLATE pg_catalog."default" NOT NULL,
    identification character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT login_customuser_pkey PRIMARY KEY (id),
    CONSTRAINT login_customuser_username_key UNIQUE (username),
    CONSTRAINT login_customuser_faculty_id_032109d2_fk_login_faculty_id FOREIGN KEY (faculty_id)
        REFERENCES public.login_faculty (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.login_customuser
    OWNER to bienestaruser;
-- Index: login_customuser_faculty_id_032109d2

-- DROP INDEX IF EXISTS public.login_customuser_faculty_id_032109d2;

CREATE INDEX IF NOT EXISTS login_customuser_faculty_id_032109d2
    ON public.login_customuser USING btree
    (faculty_id ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
-- Index: login_customuser_username_ca00b3f5_like

-- DROP INDEX IF EXISTS public.login_customuser_username_ca00b3f5_like;

CREATE INDEX IF NOT EXISTS login_customuser_username_ca00b3f5_like
    ON public.login_customuser USING btree
    (username COLLATE pg_catalog."default" varchar_pattern_ops ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;


-- Table: public.login_customuser_groups

-- DROP TABLE IF EXISTS public.login_customuser_groups;

CREATE TABLE IF NOT EXISTS public.login_customuser_groups
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    customuser_id bigint NOT NULL,
    group_id integer NOT NULL,
    CONSTRAINT login_customuser_groups_pkey PRIMARY KEY (id),
    CONSTRAINT login_customuser_groups_customuser_id_group_id_280bd5c2_uniq UNIQUE (customuser_id, group_id),
    CONSTRAINT login_customuser_gro_customuser_id_50381d88_fk_login_cus FOREIGN KEY (customuser_id)
        REFERENCES public.login_customuser (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT login_customuser_groups_group_id_639d055d_fk_auth_group_id FOREIGN KEY (group_id)
        REFERENCES public.auth_group (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.login_customuser_groups
    OWNER to bienestaruser;
-- Index: login_customuser_groups_customuser_id_50381d88

-- DROP INDEX IF EXISTS public.login_customuser_groups_customuser_id_50381d88;

CREATE INDEX IF NOT EXISTS login_customuser_groups_customuser_id_50381d88
    ON public.login_customuser_groups USING btree
    (customuser_id ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
-- Index: login_customuser_groups_group_id_639d055d

-- DROP INDEX IF EXISTS public.login_customuser_groups_group_id_639d055d;

CREATE INDEX IF NOT EXISTS login_customuser_groups_group_id_639d055d
    ON public.login_customuser_groups USING btree
    (group_id ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;


-- Table: public.login_customuser_user_permissions

-- DROP TABLE IF EXISTS public.login_customuser_user_permissions;

CREATE TABLE IF NOT EXISTS public.login_customuser_user_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    customuser_id bigint NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT login_customuser_user_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT login_customuser_user_pe_customuser_id_permission_afb8143d_uniq UNIQUE (customuser_id, permission_id),
    CONSTRAINT login_customuser_use_customuser_id_c6f5792f_fk_login_cus FOREIGN KEY (customuser_id)
        REFERENCES public.login_customuser (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT login_customuser_use_permission_id_2b8ae21e_fk_auth_perm FOREIGN KEY (permission_id)
        REFERENCES public.auth_permission (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.login_customuser_user_permissions
    OWNER to bienestaruser;
-- Index: login_customuser_user_permissions_customuser_id_c6f5792f

-- DROP INDEX IF EXISTS public.login_customuser_user_permissions_customuser_id_c6f5792f;

CREATE INDEX IF NOT EXISTS login_customuser_user_permissions_customuser_id_c6f5792f
    ON public.login_customuser_user_permissions USING btree
    (customuser_id ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
-- Index: login_customuser_user_permissions_permission_id_2b8ae21e

-- DROP INDEX IF EXISTS public.login_customuser_user_permissions_permission_id_2b8ae21e;

CREATE INDEX IF NOT EXISTS login_customuser_user_permissions_permission_id_2b8ae21e
    ON public.login_customuser_user_permissions USING btree
    (permission_id ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;


-- Table: public.login_faculty

-- DROP TABLE IF EXISTS public.login_faculty;

CREATE TABLE IF NOT EXISTS public.login_faculty
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT login_faculty_pkey PRIMARY KEY (id),
    CONSTRAINT login_faculty_name_key UNIQUE (name)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.login_faculty
    OWNER to bienestaruser;
-- Index: login_faculty_name_0f9bfd7c_like

-- DROP INDEX IF EXISTS public.login_faculty_name_0f9bfd7c_like;

CREATE INDEX IF NOT EXISTS login_faculty_name_0f9bfd7c_like
    ON public.login_faculty USING btree
    (name COLLATE pg_catalog."default" varchar_pattern_ops ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;


-- Table: public.social_projects_socialproject

-- DROP TABLE IF EXISTS public.social_projects_socialproject;

CREATE TABLE IF NOT EXISTS public.social_projects_socialproject
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    location character varying(100) COLLATE pg_catalog."default",
    start_date date,
    end_date date,
    CONSTRAINT social_projects_socialproject_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.social_projects_socialproject
    OWNER to bienestaruser;


-- Table: public.social_projects_socialprojectenrollment

-- DROP TABLE IF EXISTS public.social_projects_socialprojectenrollment;

CREATE TABLE IF NOT EXISTS public.social_projects_socialprojectenrollment
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    enrolled_at timestamp with time zone NOT NULL,
    project_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT social_projects_socialprojectenrollment_pkey PRIMARY KEY (id),
    CONSTRAINT social_projects_socialpr_user_id_project_id_07cd27ee_uniq UNIQUE (user_id, project_id),
    CONSTRAINT social_projects_soci_project_id_607ef32c_fk_social_pr FOREIGN KEY (project_id)
        REFERENCES public.social_projects_socialproject (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT social_projects_soci_user_id_50dac806_fk_login_cus FOREIGN KEY (user_id)
        REFERENCES public.login_customuser (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.social_projects_socialprojectenrollment
    OWNER to bienestaruser;
-- Index: social_projects_socialprojectenrollment_project_id_607ef32c

-- DROP INDEX IF EXISTS public.social_projects_socialprojectenrollment_project_id_607ef32c;

CREATE INDEX IF NOT EXISTS social_projects_socialprojectenrollment_project_id_607ef32c
    ON public.social_projects_socialprojectenrollment USING btree
    (project_id ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
-- Index: social_projects_socialprojectenrollment_user_id_50dac806

-- DROP INDEX IF EXISTS public.social_projects_socialprojectenrollment_user_id_50dac806;

CREATE INDEX IF NOT EXISTS social_projects_socialprojectenrollment_user_id_50dac806
    ON public.social_projects_socialprojectenrollment USING btree
    (user_id ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;


-- Table: public.tournaments_participant

-- DROP TABLE IF EXISTS public.tournaments_participant;

CREATE TABLE IF NOT EXISTS public.tournaments_participant
(
    "participantId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    team_id integer,
    tournament_id bigint NOT NULL,
    points integer NOT NULL,
    goals_conceded integer NOT NULL,
    goals_scored integer NOT NULL,
    CONSTRAINT tournaments_participant_pkey PRIMARY KEY ("participantId"),
    CONSTRAINT tournaments_particip_team_id_59ac8a48_fk_tournamen FOREIGN KEY (team_id)
        REFERENCES public.tournaments_team ("teamId") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT tournaments_particip_tournament_id_e0202941_fk_tournamen FOREIGN KEY (tournament_id)
        REFERENCES public.tournaments_tournament (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tournaments_participant
    OWNER to bienestaruser;
-- Index: tournaments_participant_team_id_59ac8a48

-- DROP INDEX IF EXISTS public.tournaments_participant_team_id_59ac8a48;

CREATE INDEX IF NOT EXISTS tournaments_participant_team_id_59ac8a48
    ON public.tournaments_participant USING btree
    (team_id ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
-- Index: tournaments_participant_tournament_id_e0202941

-- DROP INDEX IF EXISTS public.tournaments_participant_tournament_id_e0202941;

CREATE INDEX IF NOT EXISTS tournaments_participant_tournament_id_e0202941
    ON public.tournaments_participant USING btree
    (tournament_id ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;


-- Table: public.tournaments_schedule

-- DROP TABLE IF EXISTS public.tournaments_schedule;

CREATE TABLE IF NOT EXISTS public.tournaments_schedule
(
    "scheduleID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    date date NOT NULL,
    start_time time without time zone NOT NULL,
    end_time time without time zone NOT NULL,
    capacity integer NOT NULL,
    space character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tournaments_schedule_pkey PRIMARY KEY ("scheduleID"),
    CONSTRAINT tournaments_schedule_capacity_check CHECK (capacity >= 0)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tournaments_schedule
    OWNER to bienestaruser;


-- Table: public.tournaments_team

-- DROP TABLE IF EXISTS public.tournaments_team;

CREATE TABLE IF NOT EXISTS public.tournaments_team
(
    "teamId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    members text COLLATE pg_catalog."default" NOT NULL,
    tournament_id bigint NOT NULL,
    CONSTRAINT tournaments_team_pkey PRIMARY KEY ("teamId"),
    CONSTRAINT tournaments_team_tournament_id_b3f02e2a_fk_tournamen FOREIGN KEY (tournament_id)
        REFERENCES public.tournaments_tournament (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tournaments_team
    OWNER to bienestaruser;
-- Index: tournaments_team_tournament_id_b3f02e2a

-- DROP INDEX IF EXISTS public.tournaments_team_tournament_id_b3f02e2a;

CREATE INDEX IF NOT EXISTS tournaments_team_tournament_id_b3f02e2a
    ON public.tournaments_team USING btree
    (tournament_id ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;


-- Table: public.tournaments_tournament

-- DROP TABLE IF EXISTS public.tournaments_tournament;

CREATE TABLE IF NOT EXISTS public.tournaments_tournament
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    sport character varying(50) COLLATE pg_catalog."default" NOT NULL,
    gender character varying(1) COLLATE pg_catalog."default" NOT NULL,
    modality character varying(1) COLLATE pg_catalog."default" NOT NULL,
    start_date date NOT NULL,
    max_participants integer NOT NULL,
    current_participants integer NOT NULL,
    status character varying(1) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tournaments_tournament_pkey PRIMARY KEY (id),
    CONSTRAINT tournaments_tournament_max_participants_check CHECK (max_participants >= 0),
    CONSTRAINT tournaments_tournament_current_participants_check CHECK (current_participants >= 0)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tournaments_tournament
    OWNER to bienestaruser;


-- Table: public.tournaments_tournamentgame

-- DROP TABLE IF EXISTS public.tournaments_tournamentgame;

CREATE TABLE IF NOT EXISTS public.tournaments_tournamentgame
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "homeScore" integer NOT NULL,
    "guestScore" integer NOT NULL,
    played boolean NOT NULL,
    guest_player_id integer,
    guest_team_id integer,
    home_player_id integer,
    home_team_id integer,
    schedule_id integer NOT NULL,
    tournament_id bigint NOT NULL,
    CONSTRAINT tournaments_tournamentgame_pkey PRIMARY KEY (id),
    CONSTRAINT tournaments_tourname_guest_player_id_b7ee2a48_fk_tournamen FOREIGN KEY (guest_player_id)
        REFERENCES public.tournaments_participant ("participantId") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT tournaments_tourname_guest_team_id_9167b045_fk_tournamen FOREIGN KEY (guest_team_id)
        REFERENCES public.tournaments_team ("teamId") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT tournaments_tourname_home_player_id_b3452124_fk_tournamen FOREIGN KEY (home_player_id)
        REFERENCES public.tournaments_participant ("participantId") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT tournaments_tourname_home_team_id_6db452e6_fk_tournamen FOREIGN KEY (home_team_id)
        REFERENCES public.tournaments_team ("teamId") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT tournaments_tourname_schedule_id_e51f5b94_fk_tournamen FOREIGN KEY (schedule_id)
        REFERENCES public.tournaments_schedule ("scheduleID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT tournaments_tourname_tournament_id_d777f9b2_fk_tournamen FOREIGN KEY (tournament_id)
        REFERENCES public.tournaments_tournament (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tournaments_tournamentgame
    OWNER to bienestaruser;
-- Index: tournaments_tournamentgame_guest_player_id_b7ee2a48

-- DROP INDEX IF EXISTS public.tournaments_tournamentgame_guest_player_id_b7ee2a48;

CREATE INDEX IF NOT EXISTS tournaments_tournamentgame_guest_player_id_b7ee2a48
    ON public.tournaments_tournamentgame USING btree
    (guest_player_id ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
-- Index: tournaments_tournamentgame_guest_team_id_9167b045

-- DROP INDEX IF EXISTS public.tournaments_tournamentgame_guest_team_id_9167b045;

CREATE INDEX IF NOT EXISTS tournaments_tournamentgame_guest_team_id_9167b045
    ON public.tournaments_tournamentgame USING btree
    (guest_team_id ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
-- Index: tournaments_tournamentgame_home_player_id_b3452124

-- DROP INDEX IF EXISTS public.tournaments_tournamentgame_home_player_id_b3452124;

CREATE INDEX IF NOT EXISTS tournaments_tournamentgame_home_player_id_b3452124
    ON public.tournaments_tournamentgame USING btree
    (home_player_id ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
-- Index: tournaments_tournamentgame_home_team_id_6db452e6

-- DROP INDEX IF EXISTS public.tournaments_tournamentgame_home_team_id_6db452e6;

CREATE INDEX IF NOT EXISTS tournaments_tournamentgame_home_team_id_6db452e6
    ON public.tournaments_tournamentgame USING btree
    (home_team_id ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
-- Index: tournaments_tournamentgame_schedule_id_e51f5b94

-- DROP INDEX IF EXISTS public.tournaments_tournamentgame_schedule_id_e51f5b94;

CREATE INDEX IF NOT EXISTS tournaments_tournamentgame_schedule_id_e51f5b94
    ON public.tournaments_tournamentgame USING btree
    (schedule_id ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
-- Index: tournaments_tournamentgame_tournament_id_d777f9b2

-- DROP INDEX IF EXISTS public.tournaments_tournamentgame_tournament_id_d777f9b2;

CREATE INDEX IF NOT EXISTS tournaments_tournamentgame_tournament_id_d777f9b2
    ON public.tournaments_tournamentgame USING btree
    (tournament_id ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;