# Generated by Django 5.2.5 on 2025-11-09 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialproject',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='socialproject',
            name='id',
        ),
        migrations.RemoveField(
            model_name='socialproject',
            name='location',
        ),
        migrations.RemoveField(
            model_name='socialproject',
            name='start_date',
        ),
        migrations.AddField(
            model_name='socialproject',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='socialproject',
            name='projectId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='socialproject',
            name='description',
            field=models.TextField(default='Proyecto social de la universidad'),
        ),
        migrations.AlterField(
            model_name='socialproject',
            name='name',
            field=models.CharField(default='Proyecto Social Universitario', max_length=200),
        ),
        migrations.CreateModel(
            name='SocialEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='social_projects.socialproject')),
            ],
        ),
        migrations.CreateModel(
            name='SocialEventEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed', models.BooleanField(default=True)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='social_projects.socialevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_event_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscripción/Asistencia a evento',
                'verbose_name_plural': 'Inscripciones/Asistencias a eventos',
                'unique_together': {('user', 'event')},
            },
        ),
        migrations.DeleteModel(
            name='SocialProjectEnrollment',
        ),
    ]
